version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: ServerApp/Dockerfile
    container_name: chat-server
    environment:
      - DOTNET_ENVIRONMENT=Production
    ports:
      # expose UDP 9000 on host so native clients can connect too
      - "9000:9000/udp"
    command: ["dotnet", "ServerApp.dll"]

  client1:
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    container_name: chat-client-1
    depends_on: [server]
    command: ["dotnet", "ClientApp.dll", "chat-server", "9000"]

  client2:
    build:
      context: .
      dockerfile: ClientApp/Dockerfile
    container_name: chat-client-2
    depends_on: [server]
    command: ["dotnet", "ClientApp.dll", "chat-server", "9000"]
