services:
  server:
    build:
      context: .
      dockerfile: CorePunkServerSamples/Dockerfile
    container_name: chat-server
    ports:
      - "9000:9000/udp"
    command: ["dotnet", "ServerApp.dll",
              "--bind",   "0.0.0.0",
              "--target", "server",
              "--port",   "9000"]

  client1:
    build:
      context: .
      dockerfile: CorePunkClientSamples/Dockerfile
    depends_on: [server]
    container_name: chat-client-1
    command: ["dotnet", "ClientApp.dll",
              "--bind",   "0.0.0.0",
              "--target", "server",
              "--port",   "9000"]

  client2:
    build:
      context: .
      dockerfile: CorePunkClientSamples/Dockerfile
    depends_on: [server]
    container_name: chat-client-2
    command: ["dotnet", "ClientApp.dll", "server", "9000"]
