services:
  server:
    build:
      context: .
      dockerfile: CorePunkServerSamples/Dockerfile
    container_name: chat-server
    environment:
      - IP_ADDRESS=0.0.0.0
    ports:
      # expose UDP 9000 on host so native clients can connect too
      - "9000:9000/udp"
    command: ["dotnet", "ServerApp.dll", "0.0.0.0", "9000"]

  client1:
    build:
      context: .
      dockerfile: CorePunkClientSamples/Dockerfile
    container_name: chat-client-1
    depends_on: [server]
    command: ["dotnet", "ClientApp.dll", "server", "9000"]

  client2:
    build:
      context: .
      dockerfile: CorePunkClientSamples/Dockerfile
    container_name: chat-client-2
    depends_on: [server]
    command: ["dotnet", "ClientApp.dll", "server", "9000"]
