version: '3.8'
services:
  corepunkserver:
    build: ./CorePunkServerSamples
    environment:
      - APP_TYPE=server
      - APP_IPADDRESS=0.0.0.0
      - APP_PORT=8080
      - APP_USERNAME=admin
      - APP_PASSWORD=admin123
      - APP_COMMUNICATOR=UdpCommunicator
      - APP_LOGLEVEL=Info
    ports:
      - "8080:8080"